spring:
  application:
    name: guess-who
  profiles:
    active: ${env_spring_profiles_active}
  mvc:
    # noinspection SpellCheckingInspection
    problemdetails:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  docker:
    compose:
      enabled: false
  data:
    redis:
      host: ${env_redis_host}
      port: ${env_redis_port}
      username: ${env_redis_username}
      password: ${env_redis_password}
  websocket:
    message-size-limit: 10MB
    buffer-size-limit: 10MB
  session:
    timeout: 7200 # 2h - make session timeout way to long for now, for as long as http and websocket sessions are not properly integrated
    redis:
      repository-type: indexed # needed to be able to listen for redis session events
      configure-action: none
  cloud:
    aws:
      credentials:
        access-key: ${env_aws_access_key}
        secret-key: ${env_aws_secret_key}
      s3:
        region: ${env_aws_s3_region}
        endpoint: ${env_aws_s3_endpoint}
        path-style-access-enabled: true
server:
  port: ${env_application_port}
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        same-site: None
        path: /
custom:
  aws:
    s3:
      bucket: ${env_aws_s3_bucket}
  client:
    url: ${env_client_url}