spring:
  application:
    name: guess-who
  mvc:
    # noinspection SpellCheckingInspection
    problemdetails:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  docker:
    compose:
      lifecycle-management: start_and_stop
  redis:
    port: 6379
  websocket:
    message-size-limit: 10MB
    buffer-size-limit: 10MB
server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: false
        same-site: Lax
        path: /