spring:
  application:
    name: guess-who
  profiles:
    active: ${env_spring_profiles_active}
  mvc:
    # noinspection SpellCheckingInspection
    problemdetails:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  docker:
    compose:
      enabled: false
  data:
    redis:
      host: ${env_redis_host}
      port: ${env_redis_port}
  websocket:
    message-size-limit: 10MB
    buffer-size-limit: 10MB
  session:
    timeout: 7200 # 2h - make session timeout way to long for now, for as long as http and websocket sessions are not properly integrated
    redis:
      repository-type: indexed # needed to be able to listen for redis session events
      configure-action: none
server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
        same-site: None
        path: /
custom:
  application:
    url: ${env_application_url}
  client:
    url: ${env_client_url}